name: GitHub Actions SoftServe
on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Clone Repository
      uses: actions/checkout@v4
    - name: Download Dependencies
      run: mvn dependency:resolve -B
    - name: Build Maven project
      run: mvn clean install
    - name: Run Unit Tests
      run: mvn test
