name: GitHub Actions SoftServe
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Clone Repository
      uses: actions/checkout@v4
      
    - name: Download Dependencies
      run: mvn dependency:resolve -B
      
    - name: Build Maven project
      run: mvn clean install
      
    - name: Run Unit Tests
      run: mvn test

    - name: Configure Git
      run: |
        git config --global user.email "asynytsia.work@gmail.com"
        git config --global user.name "Andrii Synytsia"
      
    - name: Create and Switch to New Branch
      run: |
          git checkout -b second-task-branch
          git pull
          echo "I've changed 'README.md' using GitHub Actions" >> README.md
          git add .
          git commit -m "Update 'README.md' in second-task-branch"
          git push origin second-task-branch
      env:
        GN_TOKEN: ${{ secrets.ACCES_TOKEN }}
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
        token: ${{ secrets.ACCES_TOKEN }}
        branch: second-task-branch
        base: main
        title: "Adding some text in 'README.md' file"
        body: "Pull request for updating 'README.md' file"
        
    - name: Accept Pull Request
      uses: coderstats/github-action-merged-pull-requests@1.0.0
      with:
        token: ${{ github.event.number }}
        output: ./MERGED_PULL_REQUESTS.md
