name: GitHub Actions SoftServe
on:
  push:
  pull_request:
    types:
      - opened
      - synchronize
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps: 
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Clone Repository
      uses: actions/checkout@v4
      
    - name: Download Dependencies
      run: mvn dependency:resolve -B
      
    - name: Build Maven project
      run: mvn clean install
      
    - name: Run Unit Tests
      run: mvn test

    - name: Configure Git
      run: |
        
        git config --global user.email "asynytsia.work@gmail.com"
        git config --global user.name "Andrii Synytsia"
        
    - name: Build and analyze
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: mvn -B verify sonar:sonar -Dsonar.login=admin -Dsonar.password=password
